export const PORCENTAJE_SENIA_MIN = 0.3
export const DIAS_INHABILITACION = 30
export const CANTIDAD_CANCELACIONES_PERMITIDAS = 3
export const HORAS_MINIMAS_DEVOLUCION = 5
export const PORCENTAJE_INTERES_DIARIO = 0.01
export const TIPO_INFRACCION = {
    DEUDA: 1,
    CANCELACIONES: 2,
}
export const TIPO_ESTADOS_RESERVA = {
    TEMPORAL: 0,
    VIGENTE: 1,
    ENCURSO: 2,
    FINALIZADA: 3,
    PENDIENTE_DE_PAGO: 4,
    CANCELADA: 5,
    ASUENTE: 6,
}